name: github pages

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 安裝 Node.js 與 yarn
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        check-latest: true

    - name: 取得 yarn 的快取資料夾路徑
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: 讓 yarn 使用快取機制
      uses: actions/cache@v2
      env:
        cache-name: cache-yarn-modules
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - run: yarn
    - name: 編譯網頁
      run: yarn build

    - name: 把網頁放到 GitHub Pages 的專屬分支上
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true
